name: 'Setup Node.js and pnpm'
description: 'Common setup for Node.js, pnpm, caching, and dependency installation'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js from .nvmrc
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      # Version is automatically read from package.json's "packageManager" field

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-cache.outputs.path }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
